In [55]:
#Sebastian Acevedo 22258530
from random import choice, randint
from faker import Faker
import pandas as pd

# Inicializar Faker
fake = Faker()

# Productos y estudiantes de ejemplo

#materias = ["fisica mecanica", "estructura de datos", "programacion con php", "cts", "Calculo integral"]
estudiantes = ["hernesto", "Juan", "Sebastian", "ivan", "pedro","sandra", "andrea"]
apellidos = ["Acevedo","Restrepo","Gaviria", "Vargas", "Munoz"]


# Generar 100 estudiante aleatorias
estudiante = []

for _ in range(5):
    nomEstudiante = choice(estudiantes)
    apellidoEst = choice(apellidos)
    nota = randint(0,5)
    mate = {}     
    #for i in materias:
     #   mate[i]= randint(0,5)
    est = {
        "apellido": apellidoEst,
        "nomEstudiante": nomEstudiante,
        "fisica mecanica": randint(0,5),
        "estructura de datos": randint(0,5),
        "programacion con php": randint(0,5),
        "cts": randint(0,5),
        "Calculo integral": randint(0,5)
        
    }
  

    estudiante.append(est)
estudianteDF = pd.DataFrame(estudiante)
pd.DataFrame(estudiante)

,apellido,nomEstudiante,fisica mecanica,estructura de datos,programacion con php,cts,Calculo integral
0,Gaviria,andrea,4,1,4,0,2
1,Restrepo,Juan,5,4,4,1,3
2,Restrepo,andrea,0,4,4,2,4
3,Munoz,pedro,1,4,3,5,4
4,Restrepo,Sebastian,5,0,2,3,0

In [71]:
salir = 0
while salir ==0:    
    print("Elige una opcion:")
    print("1. Buscar estudiante")
    print("2. Listar estudiante")
    print("3. Eliminar estudiante")
    print("4. Mejor estudiante del curso")
    print("5. Mejor estudiante global")
    print("6. Peor estudiante global")
    print("7. salir")
    eleccion = int(input())
    if eleccion == 1:
        buscarNom = str(input("Introduzca el nombre del estudiante: \n"))
        buscarApe = str(input("Introduzca el Apellido del estudiante: \n"))
        #for aqui vamos!!!!------------------------------------------------ 
        if buscarApe in estudianteDF and buscarNom in estudianteDF:
            busqueda=estudianteDF.loc[(estudianteDF['apellido'] == buscarApe) & (estudianteDF['nomEstudiante'] == buscarNom) ]
            print(pd.DataFrame(busqueda))
        else:
            print('Escribiste mal el nombre o el estudiante no existe')
                
    elif eleccion ==2:
        #-------------ORGANIZAR--------------------
        x=pd.DataFrame(estudiante)
        print(x.sort_values(by='apellido'))

    elif eleccion ==3:
        buscarNom = str(input("Introduzca el nombre del estudiante: \n"))
        buscarApe = str(input("Introduzca el Apellido del estudiante: \n"))
        if buscarApe in estudiante and buscarNom in estudiante:
            print(estudianteDF.loc[:, buscarNom])
            estudiantes.remove(buscarApe)  
        print(pd.DataFrame(estudiante))
        
        
    elif eleccion ==4:
        pass
    elif eleccion ==5:
        pass
    elif eleccion ==6:
        pass
    elif eleccion ==7:
        salir = 1
        print("Haz salido con éxito")
    else:
        print("Debes escribir un número o caracter valido, intente de nuevo")

Elige una opcion:
1. Buscar estudiante
2. Listar estudiante
3. Eliminar estudiante
4. Mejor estudiante del curso
5. Mejor estudiante global
6. Peor estudiante global
7. salir
Escribiste mal el nombre o el estudiante no existe
Elige una opcion:
1. Buscar estudiante
2. Listar estudiante
3. Eliminar estudiante
4. Mejor estudiante del curso
5. Mejor estudiante global
6. Peor estudiante global
7. salir
Escribiste mal el nombre o el estudiante no existe
Elige una opcion:
1. Buscar estudiante
2. Listar estudiante
3. Eliminar estudiante
4. Mejor estudiante del curso
5. Mejor estudiante global
6. Peor estudiante global
7. salir
Escribiste mal el nombre o el estudiante no existe
Elige una opcion:
1. Buscar estudiante
2. Listar estudiante
3. Eliminar estudiante
4. Mejor estudiante del curso
5. Mejor estudiante global
6. Peor estudiante global
7. salir

ValueError: invalid literal for int() with base 10: ''